services:
  createService:
    summary: Create a new service
    value:
      request:
        name: "Brake Replacement"
        price: 149.99
        service_items:
          - item_id: 3
            quantity: 2
      response:
        status: 201
        body:
          id: 7
          name: "Brake Replacement"
          price: 149.99
          service_items:
            - id: 15
              item_id: 3
              quantity: 2
              inventory:
                id: 3
                name: "Brake Pads"
                stock: 40
                price: 30.00
              service_id: 7
              service:
                id: 7
                name: "Brake Replacement"
                price: 149.99
              mechanic_tickets: []
          mechanic_tickets: []

  getAllServices:
    summary: Retrieve all services
    value:
      response:
        status: 200
        body:
          - id: 7
            name: "Brake Replacement"
            price: 149.99
            service_items:
              - id: 15
                item_id: 3
                quantity: 2
                inventory:
                  id: 3
                  name: "Brake Pads"
                  stock: 40
                  price: 30.00
                service_id: 7
                service:
                  id: 7
                  name: "Brake Replacement"
                  price: 149.99
                mechanic_tickets: []
            mechanic_tickets: []

  getServiceById:
    summary: Retrieve a specific service by ID
    value:
      request:
        id: 7
      response:
        status: 200
        body:
          id: 7
          name: "Brake Replacement"
          price: 149.99
          service_items:
            - id: 15
              item_id: 3
              quantity: 2
              inventory:
                id: 3
                name: "Brake Pads"
                stock: 40
                price: 30.00
              service_id: 7
              service:
                id: 7
                name: "Brake Replacement"
                price: 149.99
              mechanic_tickets: []
          mechanic_tickets: []

  updateService:
    summary: Update an existing service
    value:
      request:
        id: 7
        name: "Advanced Brake Replacement"
        price: 179.99
        service_items:
          - item_id: 3
            quantity: 4
      response:
        status: 200
        body:
          id: 7
          name: "Advanced Brake Replacement"
          price: 179.99
          service_items:
            - id: 16
              item_id: 3
              quantity: 4
              inventory:
                id: 3
                name: "Brake Pads"
                stock: 38
                price: 30.00
              service_id: 7
              service:
                id: 7
                name: "Advanced Brake Replacement"
                price: 179.99
              mechanic_tickets: []
          mechanic_tickets: []
