openapi: 3.0.3
info:
  title: MechMagic AutoWorx API
  description: This API provides endpoints for managing a mechanic shop, including services, inventory, service tickets, mechanic information, and customer information.
  version: 1.0.0
servers:
  - url: http://127.0.0.1:5000
security:
  - CustomerToken: []
  - MechanicToken: []
tags:
  - name: CustomerAccount
    description: Operations for Account Information associated with Customers
  - name: Customer
    description: Operations for Customer Information
  - name: Inventory
    description: Operations for Inventory Information associated with ServiceItems
  - name: Invoices
    description: Operations for Invoice Information associated with ServiceTickets
  - name: MechanicAccount
    description: Operations for Account Information associated with Mechanics
  - name: Mechanic
    description: Operations for Mechanic Information
  - name: MechanicTicket
    description: Operations for Mechanic Ticket Information associated with Mechanics, Services, ServiceItems, and ServiceTickets
  - name: ServiceItem
    description: Operations for Service Item Information associated with Services and/or MechanicTickets
  - name: Service
    description: Operations for Service Information associated with ServiceItems and MechanicTickets
  - name: ServiceTicket
    description: Operations for Service Ticket Information associated with Customers, Vehicles, and Invoices
  - name: Vehicle
    description: Operations for Vehicle Information associated with Customers and ServiceTickets
paths: {}
components:
  schemas:
    components:
      schemas:
        Customer:
          $ref: customers.yaml#/Customer
        CustomerAccount:
          $ref: customerAccounts.yaml#/CustomerAccount
        Inventory:
          $ref: inventory.yaml#/Inventory
        Invoice:
          $ref: invoices.yaml#/Invoice
        MechanicAccount:
          $ref: mechanicAccounts.yaml#/MechanicAccount
        Mechanic:
          $ref: mechanics.yaml#/Mechanic
        MechanicTicket:
          $ref: mechanicTickets.yaml#/MechanicTicket
        ServiceItem:
          $ref: serviceItems.yaml#/ServiceItem
        Service:
          $ref: services.yaml#/Service
        ServiceTicket:
          $ref: serviceTickets.yaml#/ServiceTicket
        Vehicle:
          $ref: vehicles.yaml#/Vehicle
        CustomerUpdate:
          $ref: customerUpdate.yaml#/CustomerUpdate
        CustomerAccountUpdate:
          $ref: customerAccountUpdate.yaml#/CustomerAccountUpdate
        InventoryUpdate:
          $ref: inventoryUpdate.yaml#/InventoryUpdate
        InvoiceUpdate:
          $ref: invoiceUpdate.yaml#/InvoiceUpdate
        MechanicAccountUpdate:
          $ref: mechanicAccountUpdate.yaml#/MechanicAccountUpdate
        MechanicUpdate:
          $ref: mechanicUpdate.yaml#/MechanicUpdate
        MechanicTicketUpdate:
          $ref: mechanicTicketUpdate.yaml#/MechanicTicketUpdate
        ServiceItemUpdate:
          $ref: serviceItemUpdate.yaml#/ServiceItemUpdate
        ServiceUpdate:
          $ref: serviceUpdate.yaml#/ServiceUpdate
        ServiceTicketUpdate:
          $ref: serviceTicketUpdate.yaml#/ServiceTicketUpdate
        VehicleUpdate:
          $ref: vehicleUpdate.yaml#/VehicleUpdate
        Login:
          $ref: login.yaml#/Login
  securitySchemes:
    securitySchemes:
      CustomerToken:
        type: apiKey
        in: header
        name: Authorization
        description: |
          Use the customer Bearer token provided after login. Format: `Bearer {token}`. Token is generated via: - Algorithm: HS256 - Payload: 
            - `sub`: User ID
            - `exp`: 24 hours from issue
            - `iat`: Issued at timestamp
      MechanicToken:
        type: apiKey
        in: header
        name: Authorization
        description: |
          Use the mechanic Bearer token provided after login. Format: `Bearer {token}`. Token is generated via: - Algorithm: HS256 - Payload: 
            - `sub`: User ID
            - `role`: Always "Mechanic"
            - `exp`: 24 hours from issue
            - `iat`: Issued at timestamp
  examples:
    components:
      examples:
        LoginSuccess:
          $ref: login.yaml#/LoginSuccess
        Customer1:
          $ref: customers.yaml#/Customer1
        Customer2:
          $ref: customers.yaml#/Customer2
        Customer3:
          $ref: customers.yaml#/Customer3
        Customer4:
          $ref: customers.yaml#/Customer4
        Customer5:
          $ref: customers.yaml#/Customer5
        Customer6:
          $ref: customers.yaml#/Customer6
        AllCustomers:
          $ref: customers.yaml#/AllCustomers
        Mechanic1:
          $ref: mechanics.yaml#/Mechanic1
        Mechanic2:
          $ref: mechanics.yaml#/Mechanic2
        Mechanic3:
          $ref: mechanics.yaml#/Mechanic3
        AllMechanics:
          $ref: mechanics.yaml#/AllMechanics
  requestBodies:
    components:
      requestBodies:
        CustomerCreate:
          $ref: ./customerRequests.yaml#/CustomerCreate
        CustomerUpdate:
          $ref: ./customerRequests.yaml#/CustomerUpdate
        CustomerAccountCreate:
          $ref: ./customerAccountRequests.yaml#/CustomerAccountCreate
        CustomerAccountUpdate:
          $ref: ./customerAccountRequests.yaml#/CustomerAccountUpdate
        CustomerLogin:
          $ref: ./customerAccountRequests.yaml#/CustomerLogin
        InventoryCreate:
          $ref: ./inventoryRequests.yaml#/InventoryCreate
        InventoryUpdate:
          $ref: ./inventoryRequests.yaml#/InventoryUpdate
        InvoiceCreate:
          $ref: ./invoiceRequests.yaml#/InvoiceCreate
        InvoiceUpdate:
          $ref: ./invoiceRequests.yaml#/InvoiceUpdate
        MechanicAccountCreate:
          $ref: ./mechanicAccountRequests.yaml#/MechanicAccountCreate
        MechanicAccountUpdate:
          $ref: ./mechanicAccountRequests.yaml#/MechanicAccountUpdate
        MechanicLogin:
          $ref: ./mechanicAccountRequests.yaml#/MechanicLogin
        MechanicCreate:
          $ref: ./mechanicRequests.yaml#/MechanicCreate
        MechanicUpdate:
          $ref: ./mechanicRequests.yaml#/MechanicUpdate
        MechanicTicketCreate:
          $ref: ./mechanicTicketRequests.yaml#/MechanicTicketCreate
        MechanicTicketUpdate:
          $ref: ./mechanicTicketRequests.yaml#/MechanicTicketUpdate
        ServiceItemCreate:
          $ref: ./serviceItemRequests.yaml#/ServiceItemCreate
        ServiceItemUpdate:
          $ref: ./serviceItemRequests.yaml#/ServiceItemUpdate
        ServiceCreate:
          $ref: ./serviceRequests.yaml#/ServiceCreate
        ServiceUpdate:
          $ref: ./serviceRequests.yaml#/ServiceUpdate
        ServiceTicketCreate:
          $ref: ./serviceTicketRequests.yaml#/ServiceTicketCreate
        ServiceTicketUpdate:
          $ref: ./serviceTicketRequests.yaml#/ServiceTicketUpdate
        VehicleCreate:
          $ref: ./vehicleRequests.yaml#/VehicleCreate
        VehicleUpdate:
          $ref: ./vehicleRequests.yaml#/VehicleUpdate
  responses:
    components:
      responses:
        200Login:
          $ref: success.yaml#/200Login
        200AccountDelete:
          $ref: success.yaml#/200AccountDelete
        200CustomerDelete:
          $ref: success.yaml#/200CustomerDelete
        200MechanicDelete:
          $ref: success.yaml#/200MechanicDelete
        400Login:
          $ref: errors.yaml#/400Login
        401Login:
          $ref: errors.yaml#/401Login
        404CustomerAccount:
          $ref: errors.yaml#/404CustomerAccount
        404Customer:
          $ref: errors.yaml#/404Customer
        404Inventory:
          $ref: errors.yaml#/404Inventory
        404Invoice:
          $ref: errors.yaml#/404Invoice
        404MechanicAccount:
          $ref: errors.yaml#/404MechanicAccount
        404Mechanic:
          $ref: errors.yaml#/404Mechanic
        404MechanicTicket:
          $ref: errors.yaml#/404MechanicTicket
        404MechanicTicketServices:
          $ref: errors.yaml#/404MechanicTicketServices
        400Items:
          $ref: errors.yaml#/400Items
        404ServiceItem:
          $ref: errors.yaml#/404ServiceItem
        404ServiceTicket:
          $ref: errors.yaml#/404ServiceTicket
        404Vehicle:
          $ref: errors.yaml#/404Vehicle
