swagger: '2.0'
info:
  title: "MechMagic AutoWorx API"
  description: "This API provides endpoints for managing a mechanic shop, including services, inventory, service tickets, mechanic information, and customer information."
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

securityDefinitions:
  CustomerToken:
    type: apiKey
    name: Authorization
    in: header
    description: "Enter your customer token in the format `Bearer {token}`. This token is required for all endpoints that require specific customer authentication."

  MechanicToken:
    type: apiKey
    name: Authorization
    in: header
    description: "Enter your mechanic token in the format `Bearer {token}`. This token is required for all endpoints that require mechanic authentication."


paths: {}
definitions: {}