swagger: '2.0'
info:
  title: "MechMagic AutoWorx API"
  description: "This API provides endpoints for managing a mechanic shop, including services, inventory, service tickets, mechanic information, and customer information."
  version: "1.0.0"
host: "127.0.0.1:5000"
schemes:
  - "http"
consumes:
  - "application/json"
produces:
  - "application/json"

securityDefinitions:
  CustomerToken:
    type: apiKey
    name: Authorization
    in: header
    description: "Enter your customer token in the format `Bearer {token}`. This token is required for all endpoints that require specific customer authentication."

  MechanicToken:
    type: apiKey
    name: Authorization
    in: header
    description: "Enter your mechanic token in the format `Bearer {token}`. This token is required for all endpoints that require mechanic authentication."

paths:
  /customerAccounts:
    $ref: './paths/customerAccounts.yaml'
  /customers:
    $ref: './paths/customers.yaml'
  /inventory:
    $ref: './paths/inventory.yaml'
  /invoices:
    $ref: './paths/invoices.yaml'
  /mechanicAccounts:
    $ref: './paths/mechanicAccounts.yaml'
  /mechanics:
    $ref: './paths/mechanics.yaml'
  /mechanicTickets:
    $ref: './paths/mechanicTickets.yaml'
  /serviceItems:
    $ref: './paths/serviceItem.yaml'
  /services:
    $ref: './paths/services.yaml'
  /serviceTickets:
    $ref: './paths/serviceTickets.yaml'
  /vehicles:
    $ref: './paths/vehicles.yaml'


definitions:
#  Reusable Schemas/Models
  schemas:
    $ref: './schemas.yaml'
