components:
  schemas:
    Service:
      type: object
      required:
        - name
        - price
      properties:
        id:
          type: integer
        name:
          type: string
          minLength: 1
          maxLength: 100
        price:
          type: number
          format: float
          minimum: 0.0
        service_items:
          type: array
          items:
            $ref: "#/components/schemas/ServiceItem"
        mechanic_tickets:
          type: array
          items:
            $ref: "#/components/schemas/MechanicTicket"

    ServiceItem:
      allOf:
        - $ref: "serviceItems.yaml#/components/schemas/ServiceItem"
        - type: object
          properties:
            service_id:
              not: {}
            service:
              not: {}
            mechanic_tickets:
              not: {}

    MechanicTicket:
        allOf:
          - $ref: "mechanicTickets.yaml#/components/schemas/MechanicTicket"
          - type: object
            properties:
              hours_worked:
                not: { }
              service_ticket_id:
                not: { }
              service_ticket:
                not: { }
              mechanic:
                not: { }
              services:
                not: { }
              additional_items:
                not: { }